# SOLUCI\u00d3N DEFINITIVA - 1 SOLA CONEXI\u00d3N
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.nxwnkcuowajyiqxelnno
spring.datasource.password=Seguridad2025

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# M\u00c1XIMO 1 CONEXI\u00d3N - REUTILIZABLE
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1

server.port=8081
spring.web.cors.allowed-origins=*

logging.level.org.springframework.web=DEBUG